# Generated by Django 5.0.2 on 2024-09-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_editora_cidade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livro",
            old_name="autor",
            new_name="autores",
        ),
    ]
