# Generated by Django 5.0.2 on 2024-09-16 14:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="passage_id",
            field=models.CharField(
                default=uuid.uuid4, help_text="Passage ID", max_length=255, unique=True, verbose_name="passage_id"
            ),
        ),
    ]
